<?php
/**
 * @version   $Id: gantry.config.php 4913 2012-11-01 07:28:35Z josh $
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2013 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
defined('JPATH_BASE') or die();

$gantry_presets = array(
    'presets' => array(
        'preset1' => array(
            'name' => 'Preset 1',
            'main-accent' => '#01C5FF',
            'main-bg' => 'blue',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#2579A2',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#e1563f',
            'blocks-box2' => '#23b1bf',
            'blocks-box3' => '#ad4455',
            'blocks-box4' => '#336598'
        ),
        'preset2' => array(
            'name' => 'Preset 2',
            'main-accent' => '#01C5FF',
            'main-bg' => 'green',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#21617C',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#F1793D',
            'blocks-box2' => '#23b1bf',
            'blocks-box3' => '#8A8E2D',
            'blocks-box4' => '#2A6865'
        ),
        'preset3' => array(
            'name' => 'Preset 3',
            'main-accent' => '#F0C12F',
            'main-bg' => 'wood',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#928277',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#C45F47',
            'blocks-box2' => '#F4C432',
            'blocks-box3' => '#8A8E2D',
            'blocks-box4' => '#DB8129'
        ),
        'preset4' => array(
            'name' => 'Preset 4',
            'main-accent' => '#FEA3A8',
            'main-bg' => 'orange',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#e1563f',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#e1563f',
            'blocks-box2' => '#36C4D2',
            'blocks-box3' => '#CD2D47',
            'blocks-box4' => '#EA634D'
        ),
        'preset5' => array(
            'name' => 'Preset 5',
            'main-accent' => '#148791',
            'main-bg' => 'clouds',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'light',
            'showcasepanel-overlay' => 'light',
            'body-overlay' => 'light',
            'bottompanel-overlay' => 'light',
            'footerpanel-overlay' => 'light',
            'blocks-default' => '#3E9CCC',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#58B3E1',
            'blocks-box2' => '#33D8D6',
            'blocks-box3' => '#CD3B5A',
            'blocks-box4' => '#3E9CCC'
        ),
        'preset6' => array(
            'name' => 'Preset 6',
            'main-accent' => '#23B1BF',
            'main-bg' => 'darkblue',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#32546E',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#F6705A',
            'blocks-box2' => '#36C4D2',
            'blocks-box3' => '#CD3A5A',
            'blocks-box4' => '#3C4262'
        ),
        'preset7' => array(
            'name' => 'Preset 7',
            'main-accent' => '#23B1BF',
            'main-bg' => 'space',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#506424',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#84A837',
            'blocks-box2' => '#36C4D2',
            'blocks-box3' => '#097BB6',
            'blocks-box4' => '#0E405A'
        ),
        'preset8' => array(
            'name' => 'Preset 8',
            'main-accent' => '#22B1BF',
            'main-bg' => 'brown',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#5E4F64',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#F7705A',
            'blocks-box2' => '#36C4D2',
            'blocks-box3' => '#BD5961',
            'blocks-box4' => '#586049'
        ),
        'preset9' => array(
            'name' => 'Preset 9',
            'main-accent' => '#E29F00',
            'main-bg' => 'scene',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'light',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#d8a623',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#DC8029',
            'blocks-box2' => '#32D8D6',
            'blocks-box3' => '#B56422',
            'blocks-box4' => '#7A8246'
        ),
        'preset10' => array(
            'name' => 'Preset 10',
            'main-accent' => '#fcc44c',
            'main-bg' => 'desert',
            'main-overlay' => 'light',
            'headerpanel-overlay' => 'dark',
            'showcasepanel-overlay' => 'dark',
            'body-overlay' => 'dark',
            'bottompanel-overlay' => 'dark',
            'footerpanel-overlay' => 'dark',
            'blocks-default' => '#052844',
            'blocks-default-overlay' => 'dark',
            'blocks-box1' => '#D95626',
            'blocks-box2' => '#D95526',
            'blocks-box3' => '#B62121',
            'blocks-box4' => '#096199'
        )
    )
);
