var RokStories=new Class({version:2,Implements:[Options],options:{startElement:0,startWidth:410,startHeight:200,thumbsOpacity:0.3,autorun:true,delay:3000,scrollerDuration:1000,scrollerTransition:Fx.Transitions.Expo.easeInOut,mousetype:"click",layout:"layout1",linkedImgs:false,showThumbs:false,fixedThumb:true,mask:true,descsAnim:"topdown",imgsAnim:"bottomup",thumbLeftOffsets:{x:0,y:0},thumbRightOffsets:{x:0,y:0}},initialize:function(b,a){this.setOptions(a);
this.element=document.id(b)||null;this.layout=this.options.layout;if(!this.element){return;}if(this.layout=="layout7"){return new RokStoriesLayout7(b,a);
}this.timer=null;this.current=this.options.startElement;this.fullParent=this.element.getElements(".image-full")[0];if(this.layout=="layout6"){this.fullParent=this.element.getElements(".image-full");
}this.full=RokStoriesImage["rokstories-"+this.options.id];this.small=this.element.getElements(".image-small img");this.descs=this.element.getElements(".description");
if(this.layout=="layout2"||this.layout=="layout5"||this.layout=="layout6"){this.labels=this.element.getElements(".labels-title .feature-block-title");}if(!this.full.length||!this.small.length||(this.layout=="layout8"&&!this.descs.length)){return;
}this.images=RokStoriesImage["rokstories-"+this.options.id];this.fullFx=[];if(this.layout=="layout2"||this.layout=="layout5"){this.labelsFx=[];this.arrowLeft=this.element.getElement(".feature-arrow-l");
this.arrowRight=this.element.getElement(".feature-arrow-r");if(this.arrowLeft&&this.arrowRight){this.arrowsEvents();}(this.labels.length).times(function(c){this.labelsFx.push(new Fx.Morph(this.labels[c],{link:"cancel",duration:400,onStart:function(){this.labels[c].setStyle("visibility","visible");
}.bind(this),onComplete:function(){if(!this.labels[c].getStyle("opacity").toInt()){this.labels[c].setStyle("visibility","hidden");}}.bind(this)}).set({opacity:0}));
}.bind(this));if(this.layout=="layout5"){this.circles=this.element.getElements(".feature-number-sub");if(this.circles.length==this.small.length){this.circlesEvents();
}else{throw new Error("Circles don't match the number of images");}}}else{if(this.layout=="layout3"||this.layout=="layout4"){this.small.setStyle("display","none");
this.element.getElement(".desc-container").inject(this.fullParent).setStyles({position:"absolute","z-index":5});if(this.layout=="layout4"){this.element.getElement(".feature-numbers").inject(this.fullParent);
}this.circles=this.element.getElements(".feature-circles-sub");if(this.layout=="layout4"){this.circles=this.element.getElements(".feature-number-sub");
}if(this.circles.length==this.small.length){this.circlesEvents();}else{throw new Error("Circles don't match the number of images");}}else{if(this.layout=="layout6"){window.addEvent("load",function(){this.loaded=true;
this.featureContainer.getParent().setStyle("height",this.stories[this.current].getSize().y);this.stories.setStyle("display","block");}.bind(this));this.circles=this.element.getElements(".feature-circles-sub");
if(this.circles.length){if(this.circles.length==this.small.length){this.circlesEvents();}else{throw new Error("Circles don't match the number of images");
}}this.small.setStyle("display","none");this.stories=this.element.getElements(".feature-story");this.labelsFx=[];this.arrowLeft=this.element.getElement(".feature-arrow-l");
this.arrowRight=this.element.getElement(".feature-arrow-r");if(this.arrowLeft&&this.arrowRight){this.arrowLeft.set("title","tip");this.arrowRight.set("title","tip");
this.arrowsEvents();}(this.labels.length).times(function(c){this.labelsFx.push(new Fx.Morph(this.labels[c],{link:"cancel",duration:400,onStart:function(){this.labels[c].setStyle("visibility","visible");
},onComplete:function(){if(!this.labels[c].getStyle("opacity").toInt()){this.labels[c].setStyle("visibility","hidden");}}}).set({opacity:0}));}.bind(this));
}}}(this.images.length).times(function(c){this.fullFx.push(null);}.bind(this));this.smallFx=[];this.descsFx=[];if(this.full.length!=this.small.length&&this.full.length!=this.descs.length){return;
}this.length=this.full.length;if(this.layout!="layout6"){this.smallParent=this.small[0].getParent();this.descsParent=this.descs[0].getParent();this.fullParent.addClass("rokstories-spinner");
if(this.layout!="layout8"){this.descsParent.addClass("rokstories-spinner");}this.small.setStyle("opacity",this.options.thumbsOpacity);this.descsParentFx=new Fx.Morph(this.descsParent,{link:"cancel",duration:400});
if(this.layout!="layout8"){this.descsParentFx.set({height:0});}this.fullParentFx=new Fx.Morph(this.fullParent,{link:"cancel",duration:400}).set({height:0});
if(!window.webkit&&!window.gecko){this.fullParentFx.set({width:(window.ie)?"100%":this.options.startWidth});}this.fullParentFx.start({height:this.options.startHeight});
}else{this.fullParent[this.current].addClass("rokstories-spinner");this.featureContainer=this.element.getElement(".feature-container");this.scroller=new Fx.Scroll(this.featureContainer.getParent(),{wheelStops:false,duration:this.options.scrollerDuration,transition:this.options.scrollerTransition});
this.scroller.set(0,0);this.fullParentFx=[];this.fullParent.each(function(c,d){this.fullParentFx.push(new Fx.Morph(c,{link:"cancel",duration:400}));if(d!=this.current){this.stories[d].setStyle("display","none");
}},this);}this.mask=this.element.getElement(".image-mask");if(!this.options.mask&&this.mask){this.mask.setStyle("display","none");}this.setSizes();this.loading=true;
},addThumbsEvents:function(){var a=this,b;if(!this.storageFull){this.storageFull=[];}if(this.layout=="layout8"){b=a.element.getElement(".image-small").getChildren();
}this.small.each(function(e,d){a.smallFx.push(new Fx.Morph(e,{link:"cancel",duration:400}).set({opacity:a.options.thumbsOpacity}));var c=(a.layout=="layout8"?b[d]:e);
c.addEvents({click:function(){clearTimeout(a.timer);if(a.layout=="layout8"){b.removeClass("active");b[d].addClass("active");}if(a.layout!="layout6"){a.fullParent.addClass("rokstories-spinner");
}else{a.fullParent[d].addClass("rokstories-spinner");}if(a.layout!="layout6"){a.fullFx.each(function(g){if(g){g.start({opacity:0});}});if(a.options.layout=="layout3"||a.options.layout=="layout4"||a.options.layout=="layout5"){a.circleSwitch(d);
}}else{a.scroller.cancel().toElement(a.stories[d]);if(a.circles.length){a.circleSwitch(d);}if(a.loaded){var f=a.stories[d].getSize().y;a.featureContainer.getParent().set("tween",{duration:a.options.scrollerDuration});
a.featureContainer.getParent().tween("height",f);}}a.load(d);},mouseenter:function(){if(a.options.mousetype=="mouseenter"){e.fireEvent("click");}if(d!=a.current){a.smallFx[d].start({opacity:1});
}},mouseleave:function(){if(d!=a.current){a.smallFx[d].start({opacity:a.options.thumbsOpacity});}}});});},circlesEvents:function(){this.circles.each(function(b,a){b.addEvent("click",function(){this.small[a].fireEvent("click");
this.circleSwitch(a);}.bind(this));},this);},circleSwitch:function(a){if(this.circles){this.circles.removeClass("active");this.circles[a].addClass("active");
}},arrowsEvents:function(){var d=this.arrowLeft,c=this.arrowRight,a=this;d.addEvents({mouseenter:function(){d.addClass("arrowleft-hover");},mouseleave:function(){d.removeClass("arrowleft-hover").removeClass("arrowleft-down");
},mousedown:function(){d.addClass("arrowleft-down");},mouseup:function(){d.removeClass("arrowleft-down");},click:function(){a.previous();if(a.tipsLeft){a.tipsLeft.hide();
a.tipsLeft.fireEvent("onShow");}}});c.addEvents({mouseenter:function(){c.addClass("arrowright-hover");},mouseleave:function(){c.removeClass("arrowright-hover").removeClass("arrowright-down");
},mousedown:function(){c.addClass("arrowright-down");},mouseup:function(){c.removeClass("arrowright-down");},click:function(){a.next();if(a.tipsRight){a.tipsRight.hide();
a.tipsRight.fireEvent("onShow");}}});if(this.options.showThumbs){var b=new Element("div").setStyle("display","none");this.tipsLeft=new Tips($$(d),{className:"rokstories-tip",fixed:a.options.fixedThumb,offset:a.options.thumbLeftOffsets,onShow:function(e){if(!e){return;
}if(!e.retrieve("status")){e.store("status",true);e.setStyle("opacity",0);}var f=a.current-1;if(f<0){f=a.small.length-1;}a.small[f].clone().inject(e.empty());
e.set("tween",{duration:300,link:"cancel"});e.fade("in");},onHide:function(e){e.fade("out");}});this.tipsRight=new Tips($$(c),{className:"rokstories-tip",fixed:a.options.fixedThumb,offset:a.options.thumbRightOffsets,onShow:function(e){if(!e){return;
}if(!e.retrieve("status")){e.store("status",true);e.setStyle("opacity",0);}var f=a.current+1;if(f>a.small.length-1){f=0;}a.small[f].clone().inject(e.empty());
e.set("tween",{duration:300,link:"cancel"});e.fade("in");},onHide:function(e){e.fade("out");}});}},load:function(b){var a=this;if(typeOf(this.full[b])!="string"||this.storageFull.contains(b)){a.transition(b,this.full[b]);
a.loading=false;}else{a.storageFull.push(b);new Asset.image(this.full[b],{onload:function(){clearTimeout(a.timer);if(a.layout=="layout6"&&a.fullParent[b].getElement("img")){a.transition(b,a.full[b]);
a.loading=false;return;}if(a.layout!="layout6"){a.full[b]=this.inject(a.fullParent);}else{a.full[b]=this.inject(a.fullParent[b]);}if(a.options.linkedImgs){this.setStyle("cursor","pointer").addEvent("click",function(){window.location=RokStoriesLinks["rokstories-"+a.options.id][b].replace(/&amp;/gi,"&");
});}if(a.layout!="layout6"){a.fullFx[b]=new Fx.Morph(a.full[b],{link:"cancel",duration:400,onStart:function(){a.full[b].setStyle("visibility","visible");
},onComplete:function(){if(!a.full[b].getStyle("opacity").toInt()){a.full[b].setStyle("visibility","hidden");}}}).set({opacity:0});if(a.layout!="layout8"){a.setDescSizes.delay(70,a);
}}a.load(b);a.loading=false;}});}},transition:function(c,e){var a=this;if(this.layout!="layout6"){this.fullParentFx.cancel().set({width:e.get("width")}).start({height:e.get("height")});
}if(this.layout=="layout5"){var d=(this.options.descsAnim=="bottomup")?[this.descsHeight,0]:[-this.descsHeight,0];var b=(this.options.imgsAnim=="bottomup")?[this.descsHeight,0]:[-this.descsHeight,0];
}if(a.layout!="layout6"){a.fullParent.removeClass("rokstories-spinner");}else{a.fullParent[a.current].removeClass("rokstories-spinner");}if(a.layout!="layout8"){a.descsFx.each(function(f){f.start({opacity:0});
});}a.smallFx.each(function(f){f.start({opacity:a.options.thumbsOpacity});});if(a.layout=="layout2"||a.layout=="layout5"){a.labelsFx.each(function(f){f.start({opacity:0});
});}if(a.layout!="layout6"){if(a.options.imgsAnim=="fade"||a.options.layout!="layout5"){a.fullFx[c].cancel().start({opacity:1});}else{a.fullFx[c].cancel().start({opacity:1,top:b});
}if((a.layout=="layout2"||a.layout=="layout5")&&a.labelsFx.length){a.labelsFx[c].cancel().start({opacity:1});}if(a.layout!="layout8"){if(a.options.descsAnim=="fade"||a.options.layout!="layout5"){a.descsFx[c].cancel().start({opacity:1});
}else{a.descsFx[c].cancel().start({opacity:1,top:d});}}a.smallFx[c].cancel().start({opacity:1});}a.current=c;if(a.options.autorun&&!a.pause){a.timer=a.next.periodical(a.options.delay,a,false);
}},setSizes:function(){var a=this;if(this.layout!="layout6"&&this.layout!="layout8"){this.setDescSizes();}this.addThumbsEvents();if(this.options.autorun){this.element.addEvents({mouseenter:function(){clearTimeout(a.timer);
a.pause=true;},mouseleave:function(){clearTimeout(a.timer);a.pause=false;a.timer=a.next.periodical(a.options.delay,a,false);}});}this.next(this.current);
},setDescSizes:function(){var a={width:0,height:0};this.smallParent.setStyle("width",(this.options.startWidth=="auto")?this.fullParent.getStyle("width"):this.options.startWidth);
this.descs.each(function(c){if(this.descsFx.length<this.length){this.descsFx.push(new Fx.Morph(c,{link:"cancel",duration:400,onStart:function(){c.setStyle("visibility","visible");
},onComplete:function(){if(!c.getStyle("opacity").toInt()){c.setStyle("visibility","hidden");}}}).set({opacity:(this.layout!="layout8")?0:1}));}var b=c.getSize();
if(b.x>a.width){a.width=b.x;}if(b.y>a.height){a.height=b.y;}},this);this.descsParentFx.cancel().set("width",a.width).start({height:a.height});this.descsHeight=a.height;
if(this.layout!="layout8"){this.descsParent.removeClass("rokstories-spinner");}},next:function(a){var b=(a!==false&&typeof a!="undefined")?a:this.current+1;
if(b>this.length-1){b=0;}this.current=b;var c;if(this.layout=="layout8"){c=this.element.getElement(".image-small").getChildren();}else{c=this.small;}c[b].fireEvent("click");
},previous:function(a){var b=(a!==false&&typeof a!="undefined")?a:this.current-1;if(b<0){b=this.length-1;}this.current=b;this.small[b].fireEvent("click");
}});var RokStoriesLayout7=new Class({Implements:[Options],options:{imgWidth:960,titles:true},initialize:function(d,b){this.element=document.id(d);this.setOptions(b);
this.current=0;this.realCurrent=0;this.container=this.element.getElement(".rt-gallery-items");this.images=this.container.getChildren();this.controls=this.element.getElements(".rt-gallery-controls ul > li").filter(function(g){return !g.hasClass("previous")&&!g.hasClass("next");
});this.arrows=this.element.getElements(".rt-gallery-controls ul > li.arrow");this.container.setStyle("left",-this.options.imgWidth);this.fixFirstLast();
if(this.controls.length||this.arrows.length){this.attachEvents();}this.fx=new Fx.Tween(this.container,{duration:this.options.scrollerDuration,link:"ignore",transition:this.options.scrollerTransition}).set("left",-this.options.imgWidth);
this.titlesWrap=this.element.getElement(".rt-gallery-title");if(!this.titlesWrap){this.options.titles=false;}else{this.options.titles=true;}if(this.options.linkedImgs){this.lnkWrap=new Element("div",{"class":"layout7-lnkwrap"}).inject(this.element,"top");
var a=this.element.getElement(".rt-gallery");var c={width:a.getStyle("width")||a.getSize().x,height:a.getStyle("height")||a.getSize().y};var f=window.getSize().x-c.width.toInt();
this.lnkWrap.setStyle("left",f/2);this.lnkWrap.setStyles(c);this.lnkWrap.addEvent("click",function(){var g=this.images[this.realCurrent].getElement("img").alt;
document.location=g;}.bind(this));window.addEvent("resize",function(){var g=window.getSize().x-c.width.toInt();this.lnkWrap.setStyle("left",g/2);}.bind(this));
}if(this.options.titles){var e=0;this.titlesFx=[];this.titles=this.titlesWrap.getElements(".layout7-title");this.titles.each(function(j,g){if(!g){this.titlesWrap.setStyle("width",j.getSize().x);
}e=Math.max(e,j.getSize().x);var h=new Fx.Tween(j,{duration:this.options.scrollerDuration,link:"ignore",transition:this.options.scrollerTransition,onStart:function(){j.setStyle("visibility","visible");
},onComplete:function(){if(!j.getStyle("opacity").toInt()){j.setStyle("visibility","hidden");}}});h.set("opacity",(!g)?1:0);if(!g){j.setStyle("position","absolute");
}this.titlesFx.push(h);},this);this.titlesWrap.tween("width",e+this.titlesWrap.getStyle("margin-right").toInt());}if(this.options.autorun&&!this.pause){this.timer=this.next.periodical(this.options.delay+this.options.scrollerDuration,this,false);
}},attachEvents:function(){this.controls.each(function(c,b){var a=this.options.imgWidth*(b+1)*-1;c.addEvent("click",function(l){if(l){l.stop();}var g=this.container.getChildren().indexOf(this.images[b]),d=this.options.imgWidth*(g)*-1,f=false;
if(b==this.realCurrent){return;}if(!g||g==this.images.length-1){if(!g){var i=this.container.getStyle("left").toInt();this.container.getLast().inject(this.container,"top");
this.container.setStyle("left",i-this.options.imgWidth);d=-this.options.imgWidth;}else{var i=this.container.getStyle("left").toInt();this.container.getFirst().inject(this.container);
this.container.setStyle("left",i+this.options.imgWidth);d=this.options.imgWidth*(g-1)*-1;}}var k=this.realCurrent;this.realCurrent=b;this.current=b;this.fx.start("left",d).chain(function(){this.controls.removeClass("active");
this.controls[this.realCurrent].className=this.controls[this.realCurrent].className+" active";var e=this.container.getChildren().indexOf(this.images[this.realCurrent]);
(e-1).times(function(){this.container.getFirst().inject(this.container);this.container.setStyle("left",-this.options.imgWidth);}.bind(this));}.bind(this));
if(this.options.titles){var j=k;var h=this.realCurrent;if(h>=this.images.length){h=0;}if(Browser.ie){this.titlesFx[j].set("opacity",0).element.setStyle("visibility","hidden");
this.titlesFx[h].set("opacity",1).element.setStyle("visibility","visible");}else{this.titlesFx[j].start("opacity",0);this.titlesFx[h].start("opacity",1);
}}}.bind(this));},this);this.arrows.each(function(b,a){b.addEvent("click",function(c){c.stop();if(b.hasClass("next")){this.next();}else{this.previous();
}}.bind(this));},this);if(this.options.autorun){this.element.addEvents({mouseenter:function(){clearTimeout(this.timer);this.pause=true;}.bind(this),mouseleave:function(){clearTimeout(this.timer);
this.pause=false;this.timer=this.next.periodical(this.options.delay+this.options.scrollerDuration,this,false);}.bind(this)});}},fixFirstLast:function(){var a=this.images.getLast();
a.inject(this.container,"top");},next:function(){var d=this.images[this.realCurrent],b=this.container.getChildren().indexOf(d),a=this.container.getStyle("left").toInt();
if(b>1){(b-1).times(function(){this.container.getFirst().inject(this.container);this.container.setStyle("left",-this.options.imgWidth);a=this.container.getStyle("left").toInt();
}.bind(this));}this.fx.start("left",a-this.options.imgWidth).chain(function(){this.container.getFirst().inject(this.container);this.container.setStyle("left",-this.options.imgWidth);
this.realCurrent+=1;if(this.realCurrent>=this.images.length){this.realCurrent=0;}if(this.controls){this.controls.removeClass("active");this.controls[this.realCurrent].className=this.controls[this.realCurrent].className+" active";
}}.bind(this));if(this.options.titles){var e=this.realCurrent;var c=this.realCurrent+1;if(c>=this.images.length){c=0;}if(Browser.ie){this.titlesFx[e].set("opacity",0).element.setStyle("visibility","hidden");
this.titlesFx[c].set("opacity",1).element.setStyle("visibility","visible");}else{this.titlesFx[e].start("opacity",0);this.titlesFx[c].start("opacity",1);
}}},previous:function(){var d=this.images[this.realCurrent],b=this.container.getChildren().indexOf(d),a=this.container.getStyle("left").toInt();if(b>1){(b-1).times(function(){this.container.getLast().inject(this.container,"top");
this.container.setStyle("left",-this.options.imgWidth);a=this.container.getStyle("left").toInt();}.bind(this));}this.container.getLast().inject(this.container,"top");
this.container.setStyle("left",-(this.options.imgWidth*2));this.fx.start("left",a).chain(function(){this.realCurrent-=1;if(this.realCurrent<0){this.realCurrent=this.images.length-1;
}if(this.controls){this.controls.removeClass("active");this.controls[this.realCurrent].className=this.controls[this.realCurrent].className+" active";}}.bind(this));
if(this.options.titles){var e=this.realCurrent;var c=this.realCurrent-1;if(c<0){c=this.images.length-1;}if(Browser.ie){this.titlesFx[e].set("opacity",0).element.setStyle("visibility","hidden");
this.titlesFx[c].set("opacity",1).element.setStyle("visibility","visible");}else{this.titlesFx[e].start("opacity",0);this.titlesFx[c].start("opacity",1);
}}}});